version: "3" 
services: 
  influxdb:  
    image: influxdb:latest  
    container_name: influxdb   
    ports:   
      - "8086:8086"   
    volumes:   
      # Data persistency   
      # sudo mkdir -p /srv/docker/influxdb/data   
      - C:\Users\Kdt_T\Desktop\WiP\Ccodes\TFM_A\Persistencia\influx:/var/lib/influxdb   
  #####   
  grafana:   
    image: grafana/grafana:latest   
    container_name: grafana   
    ports:   
      - "3000:3000"   
    user: "0"   
    links:   
      - influxdb   
    volumes:   
      # Data persistency   
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data   
      - C:\Users\Kdt_T\Desktop\WiP\Ccodes\TFM_A\Persistencia\grafana:/var/lib/grafana   
